name: CF-Pferd
version: ${version}
author: ${author}
website: ${url}
api-version: ${api-version}

main: ${mainClass}
commands:
  pferd:
    description: Summons a horse
    usage: /<command>  
    permission: cf.pferd
    aliases: [Horse, horse]