name: ${artifactId}
version: ${version}
author: ${author}
website: ${url}
api-version: ${api-version}

main: ${mainClass}
commands:
  horse:
    description: Summons a horse
    usage: /<command>  
    permission: sleipnir.summon
    aliases: [pferd, horse]